version: '3.5'

services:
    postgres:
        container_name: uniscope-postgres-dev
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        networks:
            - uniscope_dev
        restart: unless-stopped
networks:
    uniscope_dev:
        name: uniscope_dev

volumes:
    postgres_data:
        name: uniscope_postgres_data
