version: '3.5'

services:
    postgres:
        container_name: ${POSTGRES_HOST}
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - postgres_data:/var/lib/postgresql/data
