ARG DOCKER_REGISTRY

FROM ${DOCKER_REGISTRY}/uniscope-base as uniscope-frontend-builder

WORKDIR /usr/src/uniscope

RUN turbo build:prod --filter=frontend

FROM nginx:latest as uniscope-frontend

COPY --from=uniscope-frontend-builder /usr/src/uniscope/apps/frontend/dist /usr/share/nginx/html
COPY --from=uniscope-frontend-builder /usr/src/uniscope/apps/frontend/nginx.conf /etc/nginx/
