version: '3.5'

services:
    pgadmin:
        container_name: uniscope-admin
        image: dpage/pgadmin4:latest
        environment:
            - VITE_HOST=${VITE_HOST}
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
            - PGADMIN_LISTEN_PORT=80
            - SCRIPT_NAME=/admin
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.uniscope-admin.entrypoints=https"
            - "traefik.http.routers.uniscope-admin.rule=Host(`${VITE_HOST}`) && PathPrefix(`/admin`)"
            - "traefik.http.routers.uniscope-admin.service=uniscope-admin"
            - "traefik.http.services.uniscope-admin.loadbalancer.server.port=80"
            - "traefik.http.routers.uniscope-admin.tls=true"
            - "traefik.http.routers.uniscope-admin.tls.certresolver=letsEncrypt"
