version: '3.5'

services:
    pgadmin:
        container_name: uniscope-admin-dev
        image: dpage/pgadmin4:latest
        environment:
            - VITE_HOST=${VITE_HOST}
            - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
            - PGADMIN_LISTEN_PORT=80
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        ports:
            - "80:80"
        networks:
            - uniscope_dev
        restart: unless-stopped

networks:
    uniscope_dev:
        external:
            name: uniscope_dev

volumes:
    pgadmin_data:
        name: uniscope_pgadmin_data
