version: '3.5'

services:
    prometheus:
        image: prom/prometheus:v2.43.0
        container_name: ${PROMETHEUS_HOST}
        environment:
            PROMETHEUS_HOST: ${PROMETHEUS_HOST}
        volumes:
            - prometheus_data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
