global:
    scrape_interval: 15s

scrape_configs:
    # Node metrics
    -   job_name: node
        static_configs:
            -   targets: [ 'uniscope-node_exporter:9100' ]
    # Docker container metrics
    -   job_name: cadvisor
        static_configs:
            -   targets: [ 'uniscope-cadvisor:8080' ]
    # Backend metrics
    -   job_name: backend
        static_configs:
            -   targets: [ 'uniscope-backend:3000' ]
