version: '3.5'

services:
    minio:
        container_name: uniscope-minio-dev
        image: minio/minio
        command: server --console-address ":9090" /data/minio
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3
        volumes:
            - minio_data:/data/minio
        ports:
            - "9000:9000"
            - "9090:9090"

networks:
    uniscope_dev:
        external:
            name: uniscope_dev

volumes:
    minio_data:
        name: uniscope_minio_data
