version: '3.5'

services:
    minio:
        container_name: uniscope-minio
        image: minio/minio
        command: server --console-address ":9090" /data/minio
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
            - MINIO_BROWSER_REDIRECT_URL=https://${VITE_HOST}/minio-console
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3
        volumes:
            - minio_data:/data
        expose:
            - 9000
            - 9090
        labels:
            - "traefik.enable=true"
            # Minio Console
            - "traefik.http.routers.uniscope-minio-console_r.entrypoints=https"
            - "traefik.http.routers.uniscope-minio-console_r.rule=Host(`${VITE_HOST}`) && PathPrefix(`/minio-console`)"
            - "traefik.http.middlewares.minio-strip-prefix.stripprefix.prefixes=/minio-console"
            - "traefik.http.routers.uniscope-minio-console_r.middlewares=minio-strip-prefix"
            - "traefik.http.routers.uniscope-minio-console_r.service=uniscope-minio-console_s"
            - "traefik.http.services.uniscope-minio-console_s.loadbalancer.server.port=9090"
            - "traefik.http.routers.uniscope-minio-console_r.tls=true"
            - "traefik.http.routers.uniscope-minio-console_r.tls.certresolver=letsEncrypt"
            # Minio s3
            - "traefik.http.routers.uniscope-minio-s3_r.entrypoints=https"
            - "traefik.http.routers.uniscope-minio-s3_r.rule=Host(`${VITE_HOST}`) && PathPrefix(`/static`)"
            - "traefik.http.routers.uniscope-minio-s3_r.middlewares=rate_limit@file"
            - "traefik.http.routers.uniscope-minio-s3_r.service=uniscope-minio-s3_s"
            - "traefik.http.services.uniscope-minio-s3_s.loadbalancer.server.port=9000"
            - "traefik.http.routers.uniscope-minio-s3_r.tls=true"
            - "traefik.http.routers.uniscope-minio-s3_r.tls.certresolver=letsEncrypt"
