version: '3.5'

services:
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.47.1
        container_name: uniscope-cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /etc/machine-id:/etc/machine-id:ro
        privileged: true
